import * as backend from "@epicmkt/backend";
import * as live from "./live.js";
import * as mock from "./mock.js";

const impl = import.meta.env?.VITE_API_MODE === "live" ? live : mock;

export const getSellerBusiness = (sellerId) => backend.getSellerBusiness(sellerId);
export const getSellerStats = (sellerId) => backend.getSellerStats(sellerId);
export const updateSellerBusiness = (sellerId, patch) => backend.updateSellerBusiness(sellerId, patch);
export const getCategories = () => backend.getCategories();

export const login = (...a) => impl.login(...a);
export const logout = (...a) => impl.logout(...a);
export const forgotRequest = (...a) => impl.forgotRequest(...a);
export const forgotVerify = (...a) => impl.forgotVerify(...a);
export const requestOtp = (...a) => impl.requestOtp(...a);
export const changePassword = (...a) => impl.changePassword(...a);
export const updateProfile = (...a) => impl.updateProfile(...a);
export const requestChange = (...a) => impl.requestChange(...a);
export const cancelChange = (...a) => impl.cancelChange(...a);
export const listChanges = (...a) => impl.listChanges(...a);
export const confirmPrices = (...a) => impl.confirmPrices(...a);
export const replyFlag = (...a) => impl.replyFlag(...a);
export const markRead = (...a) => impl.markRead(...a);
export const pauseListing = (...a) => impl.pauseListing(...a);
export const requestDeletion = (...a) => impl.requestDeletion(...a);
export const catalogStats = (...a) => impl.catalogStats(...a);
export const itemSignals = (...a) => impl.itemSignals(...a);
export const finalizeMedia = (...a) => impl.finalizeMedia(...a);
export const exportData = (...a) => impl.exportData(...a);
export const getCatalogContext = (...a) => impl.getCatalogContext(...a);
export const listItems = (...a) => impl.listItems(...a);
export const createItem = (...a) => impl.createItem(...a);
export const updateItem = (...a) => impl.updateItem(...a);
export const deleteItem = (...a) => impl.deleteItem(...a);
export const restoreItem = (...a) => impl.restoreItem(...a);
export const reorderItems = (...a) => impl.reorderItems(...a);
export const getCatalogSettings = (...a) => impl.getCatalogSettings(...a);
export const saveCatalogSettings = (...a) => impl.saveCatalogSettings(...a);
export const listItemHistory = (...a) => impl.listItemHistory(...a);
export { ApiError } from "./errors.js";
